before_script:
  - composer require atoum/atoum

script: vendor/bin/atoum

install:
<<<<<<< HEAD
=======
  - ./bin/ci/install_dependencies.sh
>>>>>>> cdb0d604245bdac602dba73a4adaea12d7542181
  - php vendor/vendors.php

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly


