language: php

php:
  - '7.0'
  - '7.1'


before_script:
  - cp .env.travis .end
  - mysql -e 'create database homestead_test;'
  - composer self-update




script: 
  - vendor/bin/phpunit
  - composer require atoum/atoum

 


