before_script:
  - composer require atoum/atoum

script: vendor/bin/atoum

install:
  - php vendor/vendors.php

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly


